name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build 

    - name: Execute unit tests
      run: dotnet test

    - name: Publish
      run: dotnet publish ./Project.csproj -c Release -o ${{ env.DOTNET_ROOT }}/app
      
    - name: Upload 
      uses: actions/upload-artifact@v3.1.0
      with:
        name: .net-app
        path: ${{ env.DOTNET_ROOT }}/app
      
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AplikacjeWeb'
          slot-name: 'Production'
          publish-profile: ${{ secrets.DEPLOY_DEV }}
          package: .
        
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AplikacjeWeb'
          slot-name: 'Production'
          publish-profile: ${{ secrets.DEPLOY_PROD }}
          package: .
